### ISSUE TITLE
Implement Specific Campus Information Component

### ISSUE THREAD

**Issue by mundoe1999** [mundoe1999/CRUD-Student-Front-End#11]
Should include all the information regarding the campus, in order for it to be displayed within the Campus page, once selected.

**Comment by LawrenceCastillo** [comment]
- see details about a single campus, including enrolled students (if any)
- see an informative message if no students are enrolled at that campus
- navigate to any student’s single student view 
- delete the campus (and elegantly handle associated students)
- edit campus information (including adding/removing students)
    -> with a validated form displaying real-time error messages
    -> which redirects back to the single campus view
